### ISSUE TITLE
Topics don't support wildcards

### ISSUE THREAD

**Issue by mhusinsky** [vvvv/VL.IO.M2MQTT#1]
are wildcards in topics supported yet?

### '+' wildcard
a topic like `foo/+/bar` does not receive messages published at `foo/1/bar` or `foo/2/bar` etc.

### '#' wildcard
when setting a receiver to a topic like `foo/bar/#`, the MQTTClient node immediately looses the connection and cannot be recovered/reconnected, even when changing the topic back to a simple one like `foo/bar/1` . the patch has to be restarted.

[edit: mixup of + and # in first version of post]

**Comment by joreg** [comment]
i'm afraid this seems to be an issue with the underlying library, see: https://github.com/eclipse/paho.mqtt.m2mqtt/issues/94
even though someone there says it works, it doesn't seem to..

i think we might need to change to another lib at some point.

**Comment by mhusinsky** [comment]
for an alternative, this looks like a well maintained project (did not look at it in detail though):
https://github.com/chkr1011/MQTTnet
https://www.nuget.org/packages/MQTTnet/

there is also a "Managed Client" in a separate nuget, if you don't need all the functionality of a server/broker:
https://github.com/chkr1011/MQTTnet/wiki/ManagedClient
https://www.nuget.org/packages/MQTTnet.Extensions.ManagedClient/

**Comment by joreg** [comment]
for an alternative MQTT pack supporting wildcards, see: https://www.nuget.org/packages/VL.IO.MQTTnet
