### ISSUE TITLE
Receivers do not resubscribe on reconnect 

### ISSUE THREAD

**Issue by TobyKLight** [vvvv/VL.IO.M2MQTT#3]
This is not always a problem because if your client ID didn't change than your old subscriptions remain in place. 

However if the server goes down OR you change your client ID and reconnect you will lose your old subscriptions. And your little receivers won't know, they will sit there and wait for subscriptions the server does not know about. 

Solution could be an IsConnected check in the Receiver (reactive) node so it sends subscribe/unsubscribe on Connected instead of Assigned. 

Workaround is manually stopping starting the whole patch (F8 F5) will resend the subscribe messages.

**Comment by antongit** [comment]
Closed by: 790aa3d4669f4c1fbc5d73b355acabe4c33c5e8b
