### ISSUE TITLE
MQTT Client does not get disposed

### ISSUE THREAD

**Issue by BenTec3d** [vvvv/VL.IO.M2MQTT#4]
The MQTT client stays connected in the background after closing the application unless closed through task manager.
Can be fixed by assigning a Disconnect node to the Dispose operation surrounded by an if block controlled by IsAssigned:

![MQTT Disconnect on Dispose](https://user-images.githubusercontent.com/33530892/119208106-fa314a00-baa0-11eb-9d76-1fc69c487f2e.png)

**Comment by joreg** [comment]
thanks for the report, fixed in nuget 1.0.12
